version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
