version: '3.8'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
volumes:
  postgres-data: