version: '3.8'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    networks:
      - app-network 
  server:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: